name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['10']  
        
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-    - name: Set up JDK 10
          
    - name: Set up JDK 10
      uses: actions/setup-java@v1
      with:
         java-version: 10
   
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Make test directory
      run: mkdir test-scratch
           
    - name: Build with Gradle
      run: ./gradlew test -i --continue -PsonatypeUsername=None -PsonatypePassword=None

