name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew and make directory
      run: chmod +x gradlew
           mkdir test-scratch
           
    - name: Build with Gradle
      run: ./gradlew test -PsonatypeUsername=None -PsonatypePassword=None
